# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'GoogleMobileVision.Xamarin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleMobileVision.Xamarin
  pod 'GoogleMobileVision'

  target 'GoogleMobileVision.XamarinTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DemoProjectiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleMobileVision.Xamarin
  pod 'GoogleMobileVision'
end

def xcode12_arch_post_install_fix(installer)
  projects = installer.aggregate_targets
    .map{ |t| t.user_project }
    .uniq{ |p| p.path }
    .push(installer.pods_project)

   arm_value = `/usr/sbin/sysctl -n hw.optional.arm64 2>&1`.to_i

   projects.each do |project|
    project.build_configurations.each do |config|
      if arm_value == 1 then
        config.build_settings.delete("EXCLUDED_ARCHS[sdk=iphonesimulator*]")
      else
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end

     project.save()
  end
end

post_install do |installer|
  xcode12_arch_post_install_fix(installer)
end