# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'GoogleMobileVision.Xamarin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleMobileVision.Xamarin
  pod 'GoogleMobileVision', '~> 1.5.0'

  target 'GoogleMobileVision.XamarinTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DemoProjectiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleMobileVision.Xamarin
  pod 'GoogleMobileVision'
end